trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: |
      # Install k6
      apt-get update && apt-get install -y curl
      curl -sSLf https://dl.k6.io/install.sh | sh
      
      # Fetch the stress test script from GitHub
      curl -sSLf -o stress_test.js https://github.com/MarcHedeby/BygSpyTestExample/blob/master/BygSpyTestExample/stress_test.js
      
      # Run the k6 stress test script
      k6 run stress_test.js

    displayName: 'Run k6 Stress Test'
