trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: |
      # Download and extract k6 binary
      curl -sSLf -o k6.tar.gz https://github.com/loadimpact/k6/releases/download/v0.34.1/k6-v0.34.1-linux-amd64.tar.gz
      tar xzvf k6.tar.gz

      # List the contents of the extracted directory for debugging
      ls -l k6-v0.34.1-linux-amd64

      # Move k6 binary to a directory in PATH
      sudo mv k6-v0.34.1-linux-amd64/k6 /usr/local/bin/k6
      
      # Verify k6 installation
      k6 version
      
      # Fetch the stress test script from GitHub
      curl -sSLf -o k6scripts.yml https://github.com/MarcHedeby/BygSpyTestExample/raw/master/k6scripts.yml
      
      # Run the k6 stress test script
      k6 run k6scripts.yml

    displayName: 'Run k6 Stress Test'
