name: Push to GitHub on Pipeline Success

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run Azure DevOps Pipeline
        run: |
          # Run your Azure DevOps pipeline here
          # Example: az pipelines run --name MyPipeline

  push_to_github:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ success() }}  # Only run if the previous job succeeded

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add more steps as needed for your workflow, such as building artifacts, deploying, etc.
      - name: Push to GitHub
        run: |
          git config --global user.email "Marc@hedeby.net"
          git config --global user.name "Stopthispasswordshit"
          git add .
          git commit -m "Update"
          git push
